name: 'Pull Request Template'
description: 'PR 작성 시 사용하는 기본 템플릿입니다.'
title: '[Feature] PR 제목을 작성해주세요'
body:
  - type: input
    id: parentKey
    attributes:
      label: '🎟️ 상위 작업 (Ticket Number)'
      description: '상위 작업의 Ticket Number를 기입해주세요'
      placeholder: 'TNT-00'
    validations:
      required: true
    
  - type: textarea
    id: what_is_pr
    attributes:
      label: '📌 What is the PR?'
      description: 'PR에 대한 전반적인 설명을 적어주세요.'
      placeholder: 'PR의 목적과 작업 내용을 간단히 설명해주세요.'
    validations:
      required: true

  - type: textarea
    id: changes
    attributes:
      label: '🪄 Changes'
      description: '작업 내용을 리스트로 작성해주세요.'
      value: |
        - ex item
    validations:
      required: true

  - type: textarea
    id: common_changes
    attributes:
      label: '🌐 Common Changes'
      description: '공통 작업 부분에 대한 수정 사항이 있다면 적어주세요.'
      placeholder: '공통으로 적용된 변경 사항을 기술해주세요.'
    validations:
      required: false

  - type: input
    id: screenshot
    attributes:
      label: '📸 Screenshot'
      description: '작업한 화면이 있다면 스크린샷이나 GIF를 첨부해주세요.'
      placeholder: '스크린샷 또는 GIF URL을 입력해주세요.'
    validations:
      required: false

  - type: textarea
    id: to_reviewers
    attributes:
      label: '🙆🏻 To Reviewers'
      description: '리뷰어에게 주목했으면 하는 점 or 바라는 점을 적어주세요.'
      placeholder: '리뷰어에게 요청 사항을 작성해주세요.'
    validations:
      required: false

  - type: textarea
    id: related_issues
    attributes:
      label: '💭 Related Issues'
      description: '작업한 이슈 번호를 # 뒤에 붙여주세요. 이슈가 닫히는 것을 원치 않으면 `Resolved:`를 지워주세요.'
      placeholder: '- Resolved: #'
    validations:
      required: false
