name: 'Basic issue template'
description: '기본 이슈 템플릿'
labels: ['feat']
title: 'Issue description'
body:
  - type: input
    id: parentKey
    attributes:
      label: '🎟️ 상위 작업 (Ticket Number)'
      description: '상위 작업의 Ticket Number를 기입해주세요 (Story)'
      placeholder: 'TNT-00'
    validations:
      required: true

  - type: input
    id: branch
    attributes:
      label: '🌳 브랜치명 (Branch)'
      description: '영어로 브랜치명을 작성해주세요'
    validations:
      required: true

  - type: textarea
    id: summary
    attributes:
      label: '🚨 이슈 요약'
      description: '이슈에 대한 내용을 간략하게 기술합니다'
      value: |
        **주요 사항**  
        - 이슈의 핵심 목표 또는 해결해야 할 문제를 간략히 작성하세요.

        **Input**  
        - 이 이슈를 수행하기 위해 필요한 입력 값, 데이터, 리소스를 작성하세요.

        **Output**  
        - 이 이슈를 통해 산출될 결과물, 목표, 또는 상태를 작성하세요.
    validations:
      required: true

  - type: textarea
    id: checklist
    attributes:
      label: '✅ 체크 리스트'
      description: '체크 리스트 타입으로 할 일을 분류합니다'
      value: |
        - [ ] 
    validations:
      required: false

  - type: textarea
    id: references
    attributes:
      label: '👀 참고자료'
      description: '참고자료(디자인 문서, API 문서 등)가 있다면 작성해주세요. 없을 경우 "없음"으로 남겨주세요.'
    validations:
      required: false
